# Generated by Django 4.0.6 on 2023-05-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=100)),
                ('organizerName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('b_group', models.CharField(max_length=5)),
                ('contact', models.CharField(max_length=10)),
                ('organizerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donationcamp.organizerdetails')),
            ],
        ),
    ]
