# Generated by Django 4.0.6 on 2023-03-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerdetails',
            name='organizerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donationcamp.organizerdetails'),
        ),
    ]
