# Generated by Django 4.0.6 on 2023-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationcamp', '0002_alter_donerdetails_organizerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donerdetails',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
