# Generated by Django 4.0.6 on 2023-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bank_name', models.CharField(max_length=100)),
                ('o_pos_group', models.IntegerField()),
                ('o_neg_group', models.IntegerField()),
                ('a_pos_group', models.IntegerField()),
                ('a_neg_group', models.IntegerField()),
                ('b_pos_group', models.IntegerField()),
                ('b_neg_group', models.IntegerField()),
                ('ab_pos_group', models.IntegerField()),
                ('ab_neg_group', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDetails', models.CharField(max_length=500)),
                ('totalQuantity', models.IntegerField(null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
