# Generated by Django 4.0.6 on 2023-05-03 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDetails', models.CharField(max_length=500)),
                ('totalQuantity', models.IntegerField(null=True)),
                ('sourceLatitude', models.FloatField()),
                ('sourceLongitude', models.FloatField()),
                ('destinationLatitude', models.FloatField()),
                ('destinationLongitude', models.FloatField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
