# Generated by Django 4.0.6 on 2023-03-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_bloodorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodorders',
            old_name='used',
            new_name='user',
        ),
    ]
